import copy

import numpy as np

from neural_decoder.lm_utils import (
    is_openai_backend,
    rescore_with_gpt2,
    score_prompted_completions,
)
from neural_decoder.section2_utils import (
    expand_candidates,
    extract_phrase_for_span,
    retrieve_confusion_context,
    sanitize_candidate_text,
    should_trigger_retrieval,
    tokenize_text,
)


def build_prompt(variant_name, candidate_pool, confusion_spans, retrieved_docs):
    lines = [
        "You are rescoring N-best transcripts from a speech BCI decoder.",
        "Only choose the candidate that best matches the evidence.",
        "Only modify confused spans when alternatives disagree.",
        "",
        "Candidates:",
    ]
    for idx, candidate in enumerate(candidate_pool, start=1):
        lines.append(f"{idx}. {candidate['text']}")

    if confusion_spans:
        lines.append("")
        lines.append("Confusion spans:")
        for span_idx, span in enumerate(confusion_spans, start=1):
            alt_parts = []
            for alternative in span["alternatives"]:
                phones = " ".join(alternative["phonemes"])
                alt_parts.append(
                    f"{alternative['text']} /{phones}/"
                )
            lines.append(
                f"{span_idx}. position {span['start']}:{span['end']} "
                f"left='{span['left_context']}' right='{span['right_context']}' "
                f"alternatives: {' | '.join(alt_parts)}"
            )

    if variant_name in {"retrieval", "full"} and retrieved_docs:
        lines.append("")
        lines.append("Retrieved context:")
        for idx, doc in enumerate(retrieved_docs, start=1):
            lines.append(f"{idx}. {doc['text']}")

    if variant_name == "full":
        lines.append("")
        lines.append(
            "Some candidates may be generated by replacing only confused spans with retrieved alternatives."
        )

    lines.append("")
    lines.append("Best option:")
    return "\n".join(lines)


def _clone_candidate(candidate):
    cloned = copy.deepcopy(candidate)
    cloned["text"] = sanitize_candidate_text(cloned["text"])
    return cloned


def build_candidate_pool(ranked_candidates, model, tokenizer, expanded_texts=None, length_penalty=0.0):
    candidate_pool = []
    seen = set()
    for candidate in ranked_candidates:
        normalized = sanitize_candidate_text(candidate["text"])
        if normalized in seen:
            continue
        item = _clone_candidate(candidate)
        item["source"] = "original"
        item["prior_score"] = float(candidate.get("total_score", candidate.get("new_lm_score", 0.0)))
        candidate_pool.append(item)
        seen.add(normalized)

    expanded_texts = expanded_texts or []
    if expanded_texts:
        if is_openai_backend(model):
            expansion_scores = [0.0] * len(expanded_texts)
        else:
            expansion_scores = rescore_with_gpt2(
                model, tokenizer, expanded_texts, length_penalty
            )
        for text, score in zip(expanded_texts, expansion_scores):
            normalized = sanitize_candidate_text(text)
            if normalized in seen:
                continue
            candidate_pool.append(
                {
                    "text": normalized,
                    "acoustic_score": 0.0,
                    "old_lm_score": 0.0,
                    "new_lm_score": float(score),
                    "total_score": float(score),
                    "confidence": 0.0,
                    "source_nbest_index": -1,
                    "source": "expanded",
                    "prior_score": float(score),
                }
            )
            seen.add(normalized)
    return candidate_pool


def prompt_rerank_candidates(
    model,
    tokenizer,
    variant_name,
    candidate_pool,
    confusion_spans,
    retrieved_docs,
    length_penalty=0.0,
    prior_weight=0.1,
):
    if not candidate_pool:
        return {"selected_text": "", "selected_score": float("-inf"), "prompt": "", "ranked": []}

    prompt = build_prompt(variant_name, candidate_pool, confusion_spans, retrieved_docs)
    completions = [f" {idx}" for idx in range(1, len(candidate_pool) + 1)]
    prompt_scores = score_prompted_completions(
        model,
        tokenizer,
        prompt,
        completions,
        length_penalty=length_penalty,
    )

    ranked = []
    for candidate, prompt_score in zip(candidate_pool, prompt_scores):
        total_score = float(prompt_score + prior_weight * candidate["prior_score"])
        item = copy.deepcopy(candidate)
        item["prompt_score"] = float(prompt_score)
        item["variant_score"] = total_score
        ranked.append(item)

    ranked.sort(key=lambda item: item["variant_score"], reverse=True)
    return {
        "selected_text": ranked[0]["text"],
        "selected_score": ranked[0]["variant_score"],
        "prompt": prompt,
        "ranked": ranked,
    }


def _replace_spans_from_votes(anchor_text, confusion_spans, chosen_phrases):
    tokens = tokenize_text(anchor_text)
    for span, replacement in sorted(
        zip(confusion_spans, chosen_phrases),
        key=lambda item: item[0]["start"],
        reverse=True,
    ):
        replacement_tokens = tokenize_text(replacement)
        tokens = tokens[: span["start"]] + replacement_tokens + tokens[span["end"] :]
    return " ".join(tokens).strip()


def multi_prompt_vote(anchor_text, confusion_spans, variant_outputs):
    if not confusion_spans:
        baseline_output = variant_outputs.get("A")
        return {
            "selected_text": baseline_output["selected_text"] if baseline_output else anchor_text,
            "votes": [],
        }

    anchor_tokens = tokenize_text(anchor_text)
    chosen_phrases = []
    vote_records = []

    for span in confusion_spans:
        phrase_votes = {}
        best_fallback = None
        best_score = float("-inf")
        for variant_name, output in variant_outputs.items():
            phrase = extract_phrase_for_span(
                anchor_tokens,
                tokenize_text(output["selected_text"]),
                span["start"],
                span["end"],
            )
            phrase_votes.setdefault(phrase, []).append(variant_name)
            if output["selected_score"] > best_score:
                best_score = output["selected_score"]
                best_fallback = phrase

        majority_phrase = None
        for phrase, voters in phrase_votes.items():
            if len(voters) >= 2:
                majority_phrase = phrase
                break
        chosen_phrase = majority_phrase if majority_phrase is not None else best_fallback
        chosen_phrases.append(chosen_phrase)
        vote_records.append(
            {
                "span": [span["start"], span["end"]],
                "votes": phrase_votes,
                "chosen_phrase": chosen_phrase,
            }
        )

    return {
        "selected_text": _replace_spans_from_votes(anchor_text, confusion_spans, chosen_phrases),
        "votes": vote_records,
    }


def apply_section2_mode(
    mode,
    ranked_candidates,
    raw_nbest,
    confusion_spans,
    score_margin,
    model,
    tokenizer,
    retriever=None,
    retrieval_top_k=5,
    phoneme_distance_threshold=3,
    score_margin_threshold=5.0,
    length_penalty=0.0,
    max_expansions=3,
):
    baseline_text = ranked_candidates[0]["text"] if ranked_candidates else ""
    baseline_score = ranked_candidates[0]["total_score"] if ranked_candidates else float("-inf")

    if mode == "ngram_top1":
        top_text = sanitize_candidate_text(raw_nbest[0][0]) if raw_nbest else ""
        return {
            "selected_text": top_text,
            "selected_score": 0.0,
            "mode": mode,
            "triggered": False,
            "retrieved_docs": [],
            "expanded_candidates": [],
            "variant_outputs": {},
        }

    if not ranked_candidates:
        return {
            "selected_text": baseline_text,
            "selected_score": baseline_score,
            "mode": mode,
            "triggered": False,
            "retrieved_docs": [],
            "expanded_candidates": [],
            "variant_outputs": {},
        }

    if mode == "llm_rescore_no_rag":
        if is_openai_backend(model):
            candidate_pool = build_candidate_pool(
                ranked_candidates,
                model,
                tokenizer,
                length_penalty=length_penalty,
            )
            variant_output = prompt_rerank_candidates(
                model,
                tokenizer,
                "baseline",
                candidate_pool,
                [],
                [],
                length_penalty=length_penalty,
            )
            return {
                "selected_text": variant_output["selected_text"],
                "selected_score": variant_output["selected_score"],
                "mode": mode,
                "triggered": False,
                "retrieved_docs": [],
                "expanded_candidates": [],
                "variant_outputs": {"A": variant_output},
            }
        return {
            "selected_text": baseline_text,
            "selected_score": baseline_score,
            "mode": mode,
            "triggered": False,
            "retrieved_docs": [],
            "expanded_candidates": [],
            "variant_outputs": {},
        }

    triggered = should_trigger_retrieval(
        confusion_spans,
        score_margin,
        phoneme_distance_threshold,
        score_margin_threshold,
    )
    retrieved_docs = []
    expanded_candidates = []

    if triggered and retriever is not None:
        retrieved_docs = retrieve_confusion_context(confusion_spans, retriever, top_k=retrieval_top_k)

    if mode in {"confusion_rag_expand", "confusion_rag_full", "multi_prompt_ensemble"} and retrieved_docs:
        expanded_candidates = expand_candidates(
            baseline_text,
            confusion_spans,
            retrieved_docs,
            max_new_candidates=max_expansions,
        )

    if mode == "confusion_rag_phoneme":
        candidate_pool = build_candidate_pool(ranked_candidates, model, tokenizer, length_penalty=length_penalty)
        variant_output = prompt_rerank_candidates(
            model,
            tokenizer,
            "phoneme",
            candidate_pool,
            confusion_spans,
            [],
            length_penalty=length_penalty,
        )
        if not triggered:
            variant_output["selected_text"] = baseline_text
            variant_output["selected_score"] = baseline_score
        return {
            "selected_text": variant_output["selected_text"],
            "selected_score": variant_output["selected_score"],
            "mode": mode,
            "triggered": triggered,
            "retrieved_docs": [],
            "expanded_candidates": [],
            "variant_outputs": {"B": variant_output},
        }

    if mode == "confusion_rag_retrieval":
        candidate_pool = build_candidate_pool(ranked_candidates, model, tokenizer, length_penalty=length_penalty)
        variant_output = prompt_rerank_candidates(
            model,
            tokenizer,
            "retrieval",
            candidate_pool,
            confusion_spans,
            retrieved_docs,
            length_penalty=length_penalty,
        )
        if not triggered:
            variant_output["selected_text"] = baseline_text
            variant_output["selected_score"] = baseline_score
        return {
            "selected_text": variant_output["selected_text"],
            "selected_score": variant_output["selected_score"],
            "mode": mode,
            "triggered": triggered,
            "retrieved_docs": retrieved_docs,
            "expanded_candidates": [],
            "variant_outputs": {"C": variant_output},
        }

    if mode in {"confusion_rag_expand", "confusion_rag_full"}:
        candidate_pool = build_candidate_pool(
            ranked_candidates,
            model,
            tokenizer,
            expanded_texts=expanded_candidates,
            length_penalty=length_penalty,
        )
        variant_output = prompt_rerank_candidates(
            model,
            tokenizer,
            "full",
            candidate_pool,
            confusion_spans,
            retrieved_docs,
            length_penalty=length_penalty,
        )
        selected_text = variant_output["selected_text"]
        if mode == "confusion_rag_full":
            voted = multi_prompt_vote(
                baseline_text,
                confusion_spans,
                {
                    "A": {"selected_text": baseline_text, "selected_score": baseline_score},
                    "C": variant_output,
                },
            )
            selected_text = voted["selected_text"]
            variant_output["votes"] = voted["votes"]
        if not triggered:
            selected_text = baseline_text
            variant_output["selected_score"] = baseline_score
        return {
            "selected_text": selected_text,
            "selected_score": variant_output["selected_score"],
            "mode": mode,
            "triggered": triggered,
            "retrieved_docs": retrieved_docs,
            "expanded_candidates": expanded_candidates,
            "variant_outputs": {"C": variant_output},
        }

    if mode == "multi_prompt_ensemble":
        candidate_pool_basic = build_candidate_pool(
            ranked_candidates,
            model,
            tokenizer,
            length_penalty=length_penalty,
        )
        candidate_pool_full = build_candidate_pool(
            ranked_candidates,
            model,
            tokenizer,
            expanded_texts=expanded_candidates,
            length_penalty=length_penalty,
        )
        if is_openai_backend(model):
            variant_a = prompt_rerank_candidates(
                model,
                tokenizer,
                "baseline",
                candidate_pool_basic,
                [],
                [],
                length_penalty=length_penalty,
            )
        else:
            variant_a = {
                "selected_text": baseline_text,
                "selected_score": baseline_score,
            }
        variant_b = prompt_rerank_candidates(
            model,
            tokenizer,
            "phoneme",
            candidate_pool_basic,
            confusion_spans,
            [],
            length_penalty=length_penalty,
        )
        variant_c = prompt_rerank_candidates(
            model,
            tokenizer,
            "full",
            candidate_pool_full,
            confusion_spans,
            retrieved_docs,
            length_penalty=length_penalty,
        )
        if not triggered:
            variant_b["selected_text"] = baseline_text
            variant_b["selected_score"] = baseline_score
            variant_c["selected_text"] = baseline_text
            variant_c["selected_score"] = baseline_score
        voted = multi_prompt_vote(
            baseline_text,
            confusion_spans,
            {"A": variant_a, "B": variant_b, "C": variant_c},
        )
        return {
            "selected_text": voted["selected_text"],
            "selected_score": max(
                variant_a["selected_score"],
                variant_b["selected_score"],
                variant_c["selected_score"],
            ),
            "mode": mode,
            "triggered": triggered,
            "retrieved_docs": retrieved_docs,
            "expanded_candidates": expanded_candidates,
            "variant_outputs": {"A": variant_a, "B": variant_b, "C": variant_c},
            "votes": voted["votes"],
        }

    return {
        "selected_text": baseline_text,
        "selected_score": baseline_score,
        "mode": mode,
        "triggered": triggered,
        "retrieved_docs": retrieved_docs,
        "expanded_candidates": expanded_candidates,
        "variant_outputs": {},
    }
