#!/usr/bin/env python3
import argparse
import json
import pickle
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from neural_decoder.section2_utils import (
    PhonemeConverter,
    build_confusion_corpus,
    read_jsonl,
    write_jsonl,
)


def load_split_transcripts(dataset_path, split_name):
    with open(dataset_path, "rb") as handle:
        dataset = pickle.load(handle)

    transcripts = []
    for session in dataset[split_name]:
        transcripts.extend(session["transcriptions"])
    return transcripts


def main():
    parser = argparse.ArgumentParser(
        description="Build the Section 2 confusion-aware retrieval corpus."
    )
    parser.add_argument(
        "--analysisJsonl",
        type=Path,
        required=True,
        help="Training-set analysis artifact generated by eval_competition.py.",
    )
    parser.add_argument(
        "--datasetPath",
        type=Path,
        default=Path("data/ptDecoder_ctc"),
        help="Dataset pickle used to mine transcript contexts.",
    )
    parser.add_argument(
        "--split",
        type=str,
        default="train",
        choices=["train", "test", "competition"],
        help="Which split to mine raw transcript contexts from.",
    )
    parser.add_argument(
        "--outputPath",
        type=Path,
        default=Path("derived/confusion_corpus.jsonl"),
        help="Where to write the confusion-aware corpus JSONL.",
    )
    parser.add_argument(
        "--countsPath",
        type=Path,
        default=Path("derived/confusion_counts.json"),
        help="Where to write the ranked confusion counts JSON.",
    )
    parser.add_argument(
        "--topKConfusions",
        type=int,
        default=100,
        help="How many frequent confusion sets to expand into corpus documents.",
    )
    parser.add_argument(
        "--docsPerPhrase",
        type=int,
        default=30,
        help="Maximum number of transcript snippets to keep per target phrase.",
    )
    args = parser.parse_args()

    analysis_path = args.analysisJsonl.expanduser().resolve()
    dataset_path = args.datasetPath.expanduser().resolve()
    output_path = args.outputPath.expanduser().resolve()
    counts_path = args.countsPath.expanduser().resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    counts_path.parent.mkdir(parents=True, exist_ok=True)

    records = read_jsonl(analysis_path)
    transcripts = load_split_transcripts(dataset_path, args.split)
    phoneme_converter = PhonemeConverter()
    corpus_docs, ranked_confusions = build_confusion_corpus(
        records,
        transcripts,
        phoneme_converter,
        top_k_confusions=args.topKConfusions,
        docs_per_phrase=args.docsPerPhrase,
    )

    write_jsonl(output_path, corpus_docs)
    with open(counts_path, "w") as handle:
        json.dump(
            [
                {"alternatives": list(alternatives), "count": count}
                for alternatives, count in ranked_confusions
            ],
            handle,
            indent=2,
        )

    print(f"Wrote {len(corpus_docs)} confusion-aware documents to {output_path}")
    print(f"Wrote {len(ranked_confusions)} ranked confusion sets to {counts_path}")


if __name__ == "__main__":
    main()
